### ISSUE TITLE
Segmentation fault: 11?

### ISSUE THREAD

**Issue by roryw10** [JoakimSoderberg/imageclipper#15]
Hi,

Im trying to use image clipper - i've installed package prerequisites using OSX and conda. Im getting the following error "Segmentation fault: 11" when i try running ./imageclipper from the file containing the images i need to clip. The executable file is in the folder containing the images. 

As an error its a bit cryptic!

**Comment by JoakimSoderberg** [comment]
Hello,

Sorry for the later reply

Did you compile it yourself? Exactly how did you compile it if that is the case?

Also I'm not sure what conda has to do with anything? You mean you used that to install the prerequisites? I need more information of exactly what you mean, exactly what dependencies you have including the versions.

A segmentation fault is of course bad, possibly due to a bug. But is there no other output whatsoever? It is quite hard to know anything unless I understand the issue in more detail

**Comment by ysyyork** [comment]
I also encountered a segment fault issue. I'm on Ubuntu 16.04 and I just followed exactly how you described in the readme to install it. No error occurs. But when I run the built executable, it raise segment fault directly. 

Sorry, actually the error message is this: "Segmentation fault (core dumped)"

**Comment by JoakimSoderberg** [comment]
@ysyyork ok could you do the following:

```bash
# ... Normal instructions
# In the build/ directory according to the instructions
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```

Now instead of just running the program by normal, run it inside of `gdb`

```bash
gdb bin/imageclipper
```

Now when you crash you should get a traceback of the exact place in the code, please paste the full backlog.

**Comment by ysyyork** [comment]
The crash comes from boost::filesystem::is_directory. I don't know. Actually I managed to run it last week and I still have a successful build of that. However, this week I want to rebuild, it throws segmentation fault again. I tried deleting boost and reinstall again it's still fail. I don't know what's going on. I just use macports to install the boost.

**Comment by ysyyork** [comment]
Well, I kind of solved the issue. I found I have two boost versions and the compile time and runtime use different boost which makes it get chaotic.

**Comment by JoakimSoderberg** [comment]
ok good to know that might happen. I'll close this then
